# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69184e8cda5deaef178c0df855d8d39cfac0ffa3e56da00ee3d50a7800bc137382c8ad61122c78e73b72a007736b7649560779e208c80a15820d1d154a39d54e

test:
  secret_key_base: 1d46fb2f717d3508c9f0658dbb5ef9eea83609ed72145cd72a7c191fe9b0189503197767ca0841cecbb47ee5eff8b8cae207a1f3d4cef9e2c28a364b44998d6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
